runtime: nodejs20

env_variables:
  # 👇 Environment variables (never commit secrets directly)
  GOOGLE_API_KEY: ${GOOGLE_API_KEY}
  NODE_ENV: production
  PORT: 8080

handlers:
  - url: /.*
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

entrypoint: npm start